apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: fights
  labels:
    strimzi.io/cluster: super-heroes
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
